language: python
dist: xenial
python:
  - "3.6" 
  - "3.7"
  - "3.8"
  - "3.9"
services:
  - postgresql
env: 
  - DJANGO=3.1.7 DB=postgres
before_install:
  - export DJANGO_SETTINGS_MODULE=projectb11.settings
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database test_db;' -U postgres
script:
  - python manage.py test