language: python
python:
  - "3.6" 
  - "3.7"
  - "3.8"
  - "3.9"
services:
  - postgresql
install:
  - pip install -r requirements.txt
env: DJANGO_SETTINGS_MODULE=projectb11.settings
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - python manage.py test