language: python
python:
  - "3.4"
  - "3.5"
  - "3.6" 
  - "3.7"
  - "3.8"
  - "3.9"
env:
  - DJANGO_VERSION=3.0.1.3
  - DJANGO_VERSION=3.1.7
  - DJANGO_VERSION=3.1.8
install:
  - pip install -r requirements.txt
script:
  - pytest