# Generated by Django 3.1.7 on 2021-03-26 20:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Other_Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('level', models.IntegerField()),
                ('xp', models.IntegerField()),
                ('friends', models.ManyToManyField(blank=True, related_name='_profile_friends_+', to='exercise_gamification.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(max_length=30)),
                ('estimated_calories', models.DecimalField(decimal_places=2, max_digits=7)),
                ('notes', models.CharField(blank=True, max_length=400)),
                ('base_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise_gamification.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Strength_Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodyweight', models.BooleanField()),
                ('repetitions', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('workout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exercise_gamification.workout')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='workouts',
            field=models.ManyToManyField(blank=True, to='exercise_gamification.Workout'),
        ),
        migrations.CreateModel(
            name='Cardio_Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DecimalField(decimal_places=2, max_digits=7)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=7)),
                ('workout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exercise_gamification.workout')),
            ],
        ),
    ]
