# Generated by Django 3.1.7 on 2021-03-29 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='other_workout',
            name='workout',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='exercise_gamification.workout'),
            preserve_default=False,
        ),
    ]
