# Generated by Django 3.1.7 on 2021-04-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_gamification', '0002_other_workout_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
