# Generated by Django 3.2 on 2021-04-19 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_gamification', '0003_auto_20210408_0153'),
        ('exercise_gamification', '0003_auto_20210419_2308'),
    ]

    operations = [
    ]
